#!/bin/sh
### BEGIN INIT INFO
# Provides:          logbulk
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Logbulk Service
### END INIT INFO

set -e

NAME="logbulk"
USERNAME="logbulk"
PIDFILE="/var/run/${NAME}.pid"
DAEMON="/opt/run/${NAME}/run.sh"
DAEMON_OPTS=""

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

. /lib/lsb/init-functions

start() {
  start-stop-daemon --background --start --quiet --make-pidfile --chuid ${USERNAME} --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
}

stop() {
  start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
}

case "$1" in
  start)
    log_daemon_msg "Starting ${NAME} service"
    start
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping ${NAME} service"
    stop
    log_end_msg $?
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
esac

exit 0