language: java
sudo: required
install: true
addons:
  sonarqube:
    token:
      secure: "pvUWminxPVDGhVP0YfpHYITs4xuRcNlwCHU0Ba4vwBhG7p8PVpYVNp+wBmQE3BcF0yg4BFNBVyc4HJdrcbrNfB16cFNvMMLp37ebX06ysbnZkVSDJ2J81HBilTuA582k/bIGmTtw28LoAdj/xJpx7+l1RoR8V/RTmKUwvusfUrWfl+CPtMcGi6csNa/8QATPigWU3QTZWJ59VqdsLWka9TzKd5/3ZGIHYczalw22VP54POJVKjAl7XFR5DBs2dTt5erz3aPV/M+30y0J0Yraje7ew0Lydpyt9UZHHdu/KaDbAne0/mwBs6Jfm8ejdyqbRfmf1mN1N5TJxM0CCb5UesCCh90g5pMREdiSQ6CT69tB+VncGLzOulSv9XAkvXih/LM5KkQQPoSwh1g8V00bhpF2cRaOV9TAkzePIfiVhiB4eqlZRWEy4xhLM/jYo/XIevFTeYf/Prrf/aDMDNn9FEnstXhWBfdhi9uXExfPRTtg1iYn8alMcojP9NIDL2JWPKzh3ky9/bbqaGiMW7n0B/u9vtIGQxGSMiKvvLu8njdcw7g3K+1YdwANGQb/orG7sjs/a1+WkmGNtYeEx1gqxATxBQW5rV2rr3UePChnkv0e0AvAb6COV4P5UG1NUo8Pe8IRibiNeY60v+xiCyATJw+0LPxTuti6/zl3bSI4Pq8="
  - openjdk8
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
jdk:
