dist: trusty
language: java
sudo: required
install: true
addons:
  sonarqube:
    token:
      secure: "gArqx2SBWfce3sSOqQM7ysuUn4YTEkx4pxM1uSVl3T8Z4DK92i+TqYZxox4WR0Z5j3hi4M0H0nhoDPazknKP12nLBlXBNU8eVpzxtjSd8LQZU1AscTROZz1fz1CBFMIAFDkLxomuOAnvANcJTqxy8XUPZboMSdK//FdIDo4+0d1C4EAcNay100k2pQfvOIy8dOXpi6PBi5LUYsXfWeuAlJ+n4ymZYzg1oQO6ccjzINGkQ+96hLql08aSBZfy5gD/ms/Fv7vFjSvqB+RGkP9wMq8jw2J/DTU30hsrYlia6+z4i29airmUImY9U7NxeT4w+x900av5XxzTRPZGnz/o9B/1+zFHM9dxGdGpbZ2tkLtZFvj95JdH1ptdCiYF0Nt6Zpwpej9TFKY23qmY82ksauw0ESKRJ4zQpkSbk/GPr6OTBpnoFfHu3oDdWb1VtjdYuCfb3NImoGhrwmHap6g1YWtU8lbiFrbSpBeCcSl+cJF/WGIosCmD1q+qnOd7XWSgXQWPpt8MVLLd17MUJtoS3cqMAoNxnZhluvSK/04SO5Z2a8ScrR/1bLnGGfTHdkCvNaw8BYMclXnTsB3iWN/qJjBpnUDB7EbA//Dq/d58l706G7BeXp2cvgFqTy/+g6r0MdzklOzbcwaRw0MNntcCaqChOLReCFOsv1KtupE8CQQ="
jdk:
  - openjdk8
  - oraclejdk8
install:
  - curl -o $HOME/.m2/settings.xml https://raw.githubusercontent.com/amannocci/logbulk/master/settings.xml
  - mvn dependency:go-offline
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test package sonar:sonar
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'
notifications:
  email: false